### ISSUE TITLE
Create NetlifyCMS to StaticCMS Migration Guide

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#46] opened 2022-10-20 23:28 UTC
Document all steps necessary to migrate from NetlifyCMS to StaticCMS, covering as many scenarios as possible.

- [ ] All deprecated features were removed
- [ ] Some widget properties/options have changed
- [ ] New markdown editor comes with new plugin interface, old editor components no longer work
- [ ] Widget control properties have changed
- [ ] List widget - Dropped support for the `field` property. A single field in the `fields` property does the same behavior.
- [ ] Dropping Moment for date-fns
- [ ] Passing a config to `.init()` will now completely override `config.yml` (they are not exclusive), instead of being merged with `config.yml`
- [ ] CMS must be explicitly initiated now.
- [ ] Dropped the following beta features from NetlifyCMS.
       - GraphQL support for GitHub and GitLab
       - Remark plugins (new markdown editor has its own plugin system)
- [ ] Dropped support for AssetStore integration
- [ ] Dropped support for Azure backend
- [ ] `registerWidget` props have changed
- [ ] `isValid` in widget control component replaced by `validator` function in `registerWidget` props
- [ ] `createClass` is deprecated, functional components should be used instead. Basic react hooks are provided as globals now.
- [ ] React 18.2.0

**Comment by mmkal** [comment] 2022-10-25 22:08
Hi! Excited to see this project. I would like to help out, as my team have built quite a bit on top of netlify-cms but we're approaching the limits of what we can do without it being maintained. I don't know if I would feel confident switching as it is, because it looks to me like a "permanent" fork. That is, in the event of Netlify assigning developers officially to netlify-cms, and it becoming an actively-maintained project - it would be bad if this fork weren't able to keep in sync. I haven't spent long looking at this, but it looks significantly different from netlify-cms. I don't doubt that the changes are _good_, but I'd have thought they make it impossible to every sync from the upstream repo ever again. Does that sound right, or do you plan on syncing from netlify-cms again some day?

**Comment by KaneFreeman** [comment] 2022-10-26 00:26
As it stands Netlify CMS is no longer maintained and it doesn't look like it will be for the foreseeable future. The last release was 6 months ago with no development being done since. [One of the authors said](https://github.com/netlify/netlify-cms/discussions/6503#discussioncomment-3202060) there were no plans for more development and no one was reviewing PRs. This combined with it looking like Netlify itself is focusing on other (paid) CMS systems to integrate with ([Contentful for example](https://www.netlify.com/on-contentful/)), and I don't see much future for Netlify CMS.

That why I forked from it. I had already made several modifications to it before making the decision, and many parts of the code proved troublesome to work with (or modify in any way reliably). So I proceeded to do a rewrite of the app completely into TypeScript. This has allowed me to get the code into a healthier state to really dive deep into it so I could better understand the code.

As for plans to ever sync with the upstream. Even if it became active again I believe this repo/project will have diverged too far from it to really ever sync again. But as I said before I do not think Netlify CMS will become active again any time soon (if ever). So I am proceeding as if its dead and moving forward.

The project right now is still unstable after the rewrite, so I would not suggest switching to it at this time. I am going through, updating the documentation and testing everything as I go. Once that task is complete (hopefully by mid November at the latest) I will release a beta version and begin working on writing a proper migration guide from Netlify CMS to Static CMS.

Right now I am using this GitHub issue to jot down things I need to remember to put in that guide when the time comes.

**Comment by KaneFreeman** [comment] 2022-10-26 00:28
Also as for the monorepo part, it is still a monorepo. The only thing I moved out was the proxy server, but that might move back in the near future as I reorganize the repo some more. What I did do though was condense all of the independent packages into a single core package. They were all used when you started up Netlify CMS anyways so it made little sense for them to be separated like that. All it did was create a lot more overhead for maintaining and releasing updates to the package.

**Comment by KaneFreeman** [comment] 2022-10-26 00:30
@mmkal if you have any feature suggestions or ideas you would want in the project in the future, feel free to open up a issue or add a comment to the [discussion board](https://github.com/StaticJsCMS/static-cms/discussions/4)!

**Comment by mmkal** [comment] 2022-10-26 02:03
Thanks for the response - I guess my concern is that this repo becomes unmaintained too, and with a small fraction of the community of netlify-cms. Are you building it supported by an organization, or just on the side? It's a huge project and I'd have thought too much for a single person to maintain, especially in their spare time. I could be wrong, though, I don't mean to be discouraging at all - and even if this project is too fresh to make sense for _my_ team, that doesn't necessarily apply to others.

(Also, I'm not sure that comment you linked was from a netlify-cms maintainer. I think it was just a person with an opinion which might or might not be well-founded. It is far from unheard of for projects to come back to life after a year or so of not much activity, especially when there's as much community interest and a commercial upsell in play)

**Comment by KaneFreeman** [comment] 2022-10-26 04:15
You are right about that comment. I read that wrong. My bad.

I am currently the only maintainer and not backed by any company.

My motavations for this project stems from using it in my own project (my church's website) and becoming frustrated with various small usability issues with Netlify CMS. So my main focus with this project is to provide a easy to use, small CMS system for static websites.

Too that end, and to help me maintain the project, I have been removing a lot of unnecessary (for the core of the cms) extra parts from the project, most notably the editorial workflow (a feature that nearly double the lines of code for the backends and parts of the UI).

**Comment by kylesloper** [comment] 2023-01-03 22:08
> Hi! Excited to see this project. I would like to help out, as my team have built quite a bit on top of netlify-cms but we're approaching the limits of what we can do without it being maintained. I don't know if I would feel confident switching as it is, because it looks to me like a "permanent" fork. That is, in the event of Netlify assigning developers officially to netlify-cms, and it becoming an actively-maintained project - it would be bad if this fork weren't able to keep in sync or merge back into netlify-cms. I haven't spent long looking at this, but it looks significantly different from netlify-cms (e.g. is it not a monorepo anymore??). I don't doubt that the changes are _good_, but I'd have thought they make it impossible to ever sync from the upstream repo again. Does that sound right, or do you plan on syncing from netlify-cms again some day?

Hey @mmkal do you happen to know if your team's work is opensource? That seems like a Goldmine if it is since I honestly believe the future of Netlify CMS (or whatever the original repo or this fork may become) relies upon its community and the extra features built by those looking for more than what's already offered. It is the only way it can survive amongst the freemium and api-based giants like Contentful and Sanity 😕

**Comment by mmkal** [comment] 2023-01-03 23:37
It isn't OSS right now, but we intend to open-source it this year. We've talked to the netlify team about the future of the netlify-cms project - and we're sticking with netlify-cms for now in hopes that it will either have people assigned to it, or at least allow the community to contribute more.

IMO, it's a bigger risk to switch to a fork like this. It seems it's made by a single person for a fairly small use case, and while I like the look of many of the tech decisions, the risk that that one person gets a new job, can't handle the scope of work, or just loses interest, seems too high. Especially given how big the differences from the original are.

**Comment by airtonix** [comment] 2023-01-07 22:22
> Also as for the monorepo part, it is still a monorepo. The only thing I moved out was the proxy server, but that might move back in the near future as I reorganize the repo some more. What I did do though was condense all of the independent packages into a single core package. They were all used when you started up Netlify CMS anyways so it made little sense for them to be separated like that. All it did was create a lot more overhead for maintaining and releasing updates to the package.

This is a myth, usually caused by improper changelog tools and version automation.

Ironically, by merging all the packages back into a monolithic package, you've now made it more likely  that maintenance is going to be problematic.

Two tools I've used in monorepos on large teams that make this a non problem : 

- [changesets](https://github.com/changesets/changesets)
- [auto](https://github.com/intuit/auto)

**Closed** 2023-01-17 15:09 UTC
Labels: documentation
